### ISSUE TITLE
Add special handling to images that have geometry inconsistencies

### ISSUE THREAD

**Issue by fedorov** [fedorov/Reporting#42]
Need to improve handling of the following 2 cases:

1. GUI usage of Reporting module, when an input label is selected, and its geometry (spacing, orientation, dimensions) do not match that of the input image. User should be given a warning about this situation, and should be given an option to create a new label (by resampling) that would match the geometry of the image.

2. For conversions of the label images using the command line script, warning should be printed on the console, but resampling should probably take place by default (https://github.com/fedorov/Reporting/blob/master/Util/LabelToDICOMSEGConverterScript.py).

@naucoin let's talk about this next time we meet.

**Comment by naucoin** [comment]
Updates made to Slicer to avoid the false positives in the geometry check:
https://github.com/Slicer/Slicer/commit/9fe70aaf70e7e24081c20e7eff7fba236eed5108

**Comment by pieper** [comment]
Nice!

**Comment by fedorov** [comment]
Thanks Nicole! Are all the pieces in the nightly so we can check with Jayashree that she is satisfied with the result?

**Comment by naucoin** [comment]
The pieces are in the Slicer nightly, but the pull request for Reporting hasn't been integrated yet: https://github.com/fedorov/Reporting/pull/45

**Comment by fedorov** [comment]
Are you waiting for me to review and merge it?

**Comment by naucoin** [comment]
@fedorov Yes

**Comment by fedorov** [comment]
Ok, I didn't realize that. You merged some pull requests in the past, so I thought you would do the same here. I will review and comment/merge.

**Comment by naucoin** [comment]
I was more waiting on the review, sorry I wasn't clear, I wanted to be sure I hit all the to-do points for this issue.

**Comment by naucoin** [comment]
I updated my github branch to use vtkImageCast and to test the converter script. I ended up having to take out the try block in order to debug it, and checked it in like that. I think that it's more important to know why the script failed since any exceptions were treated generically ("An error has occurred" was the only print out). @fedorov if you don't agree, I can put it back in.

**Comment by naucoin** [comment]
Also: it's only ensuring the cast is done after the resample, do you want to always check and cast the label map to unsigned short?

**Comment by fedorov** [comment]
> I updated my github branch to use vtkImageCast and to test the converter script. I ended up having to 
> take out the try block in order to debug it, and checked it in like that.

that's fine

> Also: it's only ensuring the cast is done after the resample, do you want to always check and cast the 
> label map to unsigned short?

since resampling is always done (at least that's how it was in my code), the cast is always applied.

**Comment by naucoin** [comment]
In my rewrite, the resampling is only done if there's a geometry mismatch, and a geometry mismatch is not detected if the scalar types don't match. Your comment from Oct 29th might have been conflating the GUI version vs the automatic script. I'll do another fix that always checks the label volume type no matter if it's been resampled or not, and ensures that it's unsigned short.

**Comment by fedorov** [comment]
I do not see harm in always resampling unless user says "no", to simplify the code and get this issue finally resolved. 

The way I thought about geometry checks is just the means to detect a situation when the user needs to be alerted, and have an option to not proceed with using a label when geometry checks identified a situation with an invalid input label selected.

**Comment by naucoin** [comment]
But this specific case is for the command line script that doesn't do user input.

**Comment by fedorov** [comment]
Oh, I see, you are saying "a geometry mismatch is not detected if the scalar types don't match". Not sure why is that, but if that is the case, sounds like cast should always be done in the script prior to geometry checks.

It probably makes sense to add a command line flag to the converter (-F for "force"?) to ignore geometry inconsistencies, and abort conversion if no such flag is specified and geometry checks fail.

**Comment by naucoin** [comment]
Scalar type isn't related to the geometry of the volume, just the contents. 
I'll pull the cast out of the resample logic and add a command line flag.

**Comment by naucoin** [comment]
Change me, could you please double check that's what you meant?

**Comment by fedorov** [comment]
Ok, although using something like ![argparse](https://docs.python.org/3/library/argparse.html) would be more robust (and more user-friendly), now that the number of arguments is not fixed.

Example: https://www.assembla.com/code/slicerrt/subversion/nodes/2178/trunk/SlicerRt/src/BatchProcessing/BatchContourConversion.py#ln281

**Comment by naucoin** [comment]
I think it's ready, here's the pull request:
https://github.com/fedorov/Reporting/pull/45

**Comment by fedorov** [comment]
#45 was merged, so this one can be closed
